import { Earthstar, Input, Select } from "../deps.ts";
import { pickReplica } from "../helpers/pick_replica.ts";

const fileExtensionRegex = /^.*\.(\w+)$/;
const endingWithKeypairAddrRegex = /^.*~@\w{4}\.\w{53}$/;

function pathHasFileExtension(path: string): boolean {
  if (path.indexOf(".") === -1) {
    return false;
  }

  // Check that it's in the right position.
  const matches = path.match(fileExtensionRegex);

  if (matches === null) {
    return false;
  }

  const extension = matches[1];

  // Is this part of a keypair address?
  if (extension.length === 53 && path.match(endingWithKeypairAddrRegex)) {
    return false;
  }

  return true;
}

const settings = new Earthstar.ClientSettings();

if (!settings.author) {
  console.error(
    "You can't write data without an author keypair. There isn't one saved in the settings.",
  );
  Deno.exit(1);
}

const replica = await pickReplica();

// Check the path.
// If it ends in an extension, pipe in bytes to attachment with auto generated document text (TODO: make this an option)
// If it's not, just read the text and write straight to the doc.
const docPath = await Input.prompt({
  message: "Choose a path",
  suggestions: await replica.queryPaths({}),
});

const shouldMakeAttachment = pathHasFileExtension(docPath);

if (shouldMakeAttachment) {
  const path = await Input.prompt({
    message: "Choose a filesystem path to read data from",
    files: true,
  });

  const file = await Deno.open(path);

  const result = await replica.set(settings.author, {
    path: docPath,
    text: "This document was generated by my cool script!",
    attachment: file.readable,
  });

  if (Earthstar.isErr(result)) {
    console.log(result.message);
    Deno.exit(1);
  }

  await replica.close(false);

  console.log(`Wrote contents of ${path} to ${docPath}`);
  Deno.exit(0);
} else {
  const text = await Input.prompt({
    message: "Enter document text",
  });

  const result = await replica.set(settings.author, {
    path: docPath,
    text: text,
  });

  if (Earthstar.isErr(result)) {
    console.log(result.message);
    Deno.exit(1);
  }

  await replica.close(false);

  console.log(`Wrote text to ${docPath}`);
  Deno.exit(0);
}
